## Production 
## this is multi_staging , like we can name the stages (alias)

FROM node:20-alpine as Building_stage
WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN npm install --include=dev
COPY . .

RUN npm run build

## stage 2 

FROM nginx:alpine
WORKDIR /app

COPY --from=Building_stage /app/dist /usr/share/nginx/html 

RUN adduser -S app_user 
USER add_user 

EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]  