## developemnt 

FROM node:20-alpine as Building_stage
WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN npm install --include=dev
COPY . .

EXPOSE 5173

RUN adduser -S app
USER app

CMD ["npm", "run" , "dev"]