FROM node:20-alpine
RUN npm install -g pnpm

WORKDIR /app

COPY ./package.json ./package.json 
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 

RUN pnpm install --include=dev

COPY . .
EXPOSE 8080

RUN adduser -S app
USER app

CMD ["pnpm", "run" , "start"]