FROM node:20-alpine
RUN npm install -g pnpm

RUN adduser -S app
USER app

WORKDIR /app

COPY ./package.json ./package.json 
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml 

RUN pnpm install --include=dev

COPY . .
EXPOSE 8080



CMD ["pnpm", "run" , "dev"]